void main(List<String> args) {
  /*
  ********Veri türleri dinamik olan liste yapma...
  var listem = [];
  ********Belirli veri türleri olan liste yapma...
  var listem1 = <String>[];*/
  /**********************************************/
  /*Setler ve mapler köşeli parantez ile tutulduğu için karışıklır olabilir.
    Ayrım yapmak için içerisine değer girilmelidir.
    ***Eğer değer girilmezse veya ikili değer girilirse map oluşur...
    ***Tek değer girilirse set oluşur...
  */
  //Map oluşturma...
  var myMap = {"Ad": "Mehmet Fatih"}; //Map olarak algılar...
  var myMap2 = <String, dynamic>{"Yaş": 22}; //MAP...
  //Set oluşturma...
  var mySet = {"Ali"}; //SET...
  var mySet2 = <int>{21, 24}; //SET...

  //Listeleri birleştirme...
  var tekSayilar = [1, 3, 5, 7, 9];
  var ciftSayilar = [0, 2, 4, 6, 8];
  var sonListe = [];

  sonListe.addAll(tekSayilar); //tekSayilar listesi eklendi...
  sonListe.addAll(ciftSayilar); //ciftSayilar listesi eklendi...
  print(sonListe);
  //Kısa yolla ekleme...
  var tekSayilar2 = [1, 3, 5, 7, 9];
  var ciftSayilar2 = [0, 2, 4, 6, 8];
  //spreads operator
  /*Kısa yol olarak 3 nokta koyarak yapabiliri.
  ***Eğer 3 nokta konmazsa tekSayilar2 listesi ile ciftSayilar2 listesi ayrı listeler olarak eklenir...
  */
  var sonListe2 = [...tekSayilar2, ...ciftSayilar2];
  print(sonListe2);

  print("*******************************************");

  //Maplerde birleştirme...
  var sonMap = {...myMap, ...myMap2};
  print(sonMap);

  print("*******************************************");

  //Setlerde birleştirme...
  var sonSet = {...mySet, ...mySet2};
  print(sonSet);
}
