void main(List<String> args) {
  List<int> sayilar = [12, 13, 15, 12, 16];
  if (sayilar.isNotEmpty) {
    print(sayilar.first);
    //Listedeki ilk elemanı verir. Eğer liste boşsa hata verir...
    print(sayilar.last);
    //Listedeki son elemanı verir. Eğer liste boşsa hata verir...
  }
  print("Liste boş mu? ${sayilar.isEmpty}");
  print("Liste uzunluğu:" + sayilar.length.toString());
  print("Ters sırada yazdır: ${sayilar.reversed}");
  //Anlık ters yazdırır verilerde değişiklik olmaz...
  print(sayilar);
  //[12,13,15,12,16] listesi için...
  sayilar.add(21);
  //15 sayısını listenin sonuna ekler...
  //Yeni liste [12,13,15,12,16,21]...
  sayilar.remove(12);
  //İlk gördüğü 12 sayısını listeden çıkarır...
  //Yeni liste [13,15,12,16,21]...
  sayilar.removeAt(0);
  //0. indexteki sayıyı listeden çıkarır...
  //Yeni liste [15,12,16,21]...

  if (sayilar.contains(15)) {
    print("15 sayısı listede var");
  } else {
    print("15 sayısı listede yok");
  }
  //Contains verilen sayı listede varsa true yoksa false döndürür...
  print(sayilar.elementAt(3));
  //Listenin 3. indexindeki elemanı döndürür...
  print(sayilar.indexOf(15));
  //Listedeki 15 elemanının indexini döndürür...
  sayilar.shuffle();
  //Listedeki elemanların yerlerini random değiştirir...
  print(sayilar);
  sayilar.clear();
  //Listedeki tüm elemanları siler...
  print(sayilar);
}
